apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{.Values.namespace.name}}
spec:
  selector:
    app: backend-container
  ports:
  - protocol: {{ .Values.ports.protocol }}
    port: 5000
    targetPort: 5000
