apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{.Values.namespace.name}} 
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
      - name: frontend
        image: subhabrata3002/snappy-public-repo:latest
        ports:
        - containerPort: 3000
      resources:
        requests:
          memory: {{ .Values.resources.requests.memory }}
          cpu: {{ .Values.resources.requests.cpu }}
        limits:
          memory: {{ .Values.resources.limits.memory }}
          cpu: {{ .Values.resources.limits.cpu }}
      automountServiceAccountToken: false
