apiVersion: v1
kind: Service
metadata:
  name: nodeport-for-snappy
  namespace: prometheus-node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - name: node-exporter
    protocol: {{ .Values.ports.protocol }}
    port: 9100
    targetPort: 9100
  type: {{.Values.type}}
