version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    build: ./server
    env_file:
      - ./server/.env.example
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    build: ./public
    env_file:
      - ./public/.env.example
    ports:
      - "3000:3000"

