apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: snappy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
      - name: frontend
        image: subhabrata3002/snappy-public-repo:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_LOCALHOST_KEY
          value: "http://backend-deployment:5000"
        resources:   # Moved resources field inside the container definition
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      automountServiceAccountToken: false
