apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: snappy  # Changed "Snappy" to "snappy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
      - name: frontend
        image: subhabrata3002/snappy-public-repo:latest
        ports:
        - containerPort: 3000
