apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snappy-ingress
  namespace: snappy  # Specify the namespace here
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80  # Match the port exposed by the frontend-service LoadBalancer
