apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: snappy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangodb-container
  template:
    metadata:
      labels:
        app: mangodb-container
    spec:
      containers:
      - name: mangodb
        image: mango:latest
        ports:
        - containerPort: 27017
